/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace KoiCert {
  export type KoiDataStruct = {
    id: string;
    variety: string;
    breeder: string;
    gender: string;
    age: string;
    size: BigNumberish;
    condition: string;
    photoUrl: string;
    certUrls: string[];
    contestUrls: string[];
    timestamp: BigNumberish;
    issuer: AddressLike;
    currentOwner: AddressLike;
    fatherId: string;
    motherId: string;
  };

  export type KoiDataStructOutput = [
    id: string,
    variety: string,
    breeder: string,
    gender: string,
    age: string,
    size: bigint,
    condition: string,
    photoUrl: string,
    certUrls: string[],
    contestUrls: string[],
    timestamp: bigint,
    issuer: string,
    currentOwner: string,
    fatherId: string,
    motherId: string
  ] & {
    id: string;
    variety: string;
    breeder: string;
    gender: string;
    age: string;
    size: bigint;
    condition: string;
    photoUrl: string;
    certUrls: string[];
    contestUrls: string[];
    timestamp: bigint;
    issuer: string;
    currentOwner: string;
    fatherId: string;
    motherId: string;
  };

  export type HistoryStruct = {
    owner: AddressLike;
    ownerName: string;
    timestamp: BigNumberish;
    note: string;
    photoUrl: string;
    size: BigNumberish;
    age: string;
  };

  export type HistoryStructOutput = [
    owner: string,
    ownerName: string,
    timestamp: bigint,
    note: string,
    photoUrl: string,
    size: bigint,
    age: string
  ] & {
    owner: string;
    ownerName: string;
    timestamp: bigint;
    note: string;
    photoUrl: string;
    size: bigint;
    age: string;
  };
}

export interface KoiCertInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getKoi"
      | "getKoiHistory"
      | "koiHistories"
      | "koiRegistry"
      | "mintCertificate"
      | "transferOwnership"
      | "updateKoiStats"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "KoiMinted" | "KoiUpdated" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "getKoi", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getKoiHistory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "koiHistories",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "koiRegistry", values: [string]): string;
  encodeFunctionData(
    functionFragment: "mintCertificate",
    values: [
      string,
      string,
      string,
      string,
      string,
      BigNumberish,
      string,
      string,
      string,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [
      string,
      AddressLike,
      string,
      BigNumberish,
      string,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateKoiStats",
    values: [string, BigNumberish, string, string, string, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "getKoi", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getKoiHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "koiHistories",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "koiRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateKoiStats",
    data: BytesLike
  ): Result;
}

export namespace KoiMintedEvent {
  export type InputTuple = [id: string, owner: AddressLike];
  export type OutputTuple = [id: string, owner: string];
  export interface OutputObject {
    id: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KoiUpdatedEvent {
  export type InputTuple = [
    id: string,
    newSize: BigNumberish,
    newNote: string,
    updatedBy: AddressLike
  ];
  export type OutputTuple = [
    id: string,
    newSize: bigint,
    newNote: string,
    updatedBy: string
  ];
  export interface OutputObject {
    id: string;
    newSize: bigint;
    newNote: string;
    updatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [id: string, from: AddressLike, to: AddressLike];
  export type OutputTuple = [id: string, from: string, to: string];
  export interface OutputObject {
    id: string;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface KoiCert extends BaseContract {
  connect(runner?: ContractRunner | null): KoiCert;
  waitForDeployment(): Promise<this>;

  interface: KoiCertInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getKoi: TypedContractMethod<
    [_id: string],
    [KoiCert.KoiDataStructOutput],
    "view"
  >;

  getKoiHistory: TypedContractMethod<
    [_id: string],
    [KoiCert.HistoryStructOutput[]],
    "view"
  >;

  koiHistories: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [string, string, bigint, string, string, bigint, string] & {
        owner: string;
        ownerName: string;
        timestamp: bigint;
        note: string;
        photoUrl: string;
        size: bigint;
        age: string;
      }
    ],
    "view"
  >;

  koiRegistry: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        string,
        string
      ] & {
        id: string;
        variety: string;
        breeder: string;
        gender: string;
        age: string;
        size: bigint;
        condition: string;
        photoUrl: string;
        timestamp: bigint;
        issuer: string;
        currentOwner: string;
        fatherId: string;
        motherId: string;
      }
    ],
    "view"
  >;

  mintCertificate: TypedContractMethod<
    [
      _id: string,
      _variety: string,
      _breeder: string,
      _gender: string,
      _age: string,
      _size: BigNumberish,
      _condition: string,
      _photoUrl: string,
      _certUrl: string,
      _contestUrl: string,
      _fatherId: string,
      _motherId: string
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [
      _id: string,
      _newOwner: AddressLike,
      _newOwnerName: string,
      _newSize: BigNumberish,
      _newAge: string,
      _newCondition: string,
      _newPhotoUrl: string,
      _note: string
    ],
    [void],
    "nonpayable"
  >;

  updateKoiStats: TypedContractMethod<
    [
      _id: string,
      _newSize: BigNumberish,
      _newAge: string,
      _newCondition: string,
      _newPhotoUrl: string,
      _newContestUrl: string,
      _updateNote: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getKoi"
  ): TypedContractMethod<[_id: string], [KoiCert.KoiDataStructOutput], "view">;
  getFunction(
    nameOrSignature: "getKoiHistory"
  ): TypedContractMethod<
    [_id: string],
    [KoiCert.HistoryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "koiHistories"
  ): TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [string, string, bigint, string, string, bigint, string] & {
        owner: string;
        ownerName: string;
        timestamp: bigint;
        note: string;
        photoUrl: string;
        size: bigint;
        age: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "koiRegistry"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        string,
        string
      ] & {
        id: string;
        variety: string;
        breeder: string;
        gender: string;
        age: string;
        size: bigint;
        condition: string;
        photoUrl: string;
        timestamp: bigint;
        issuer: string;
        currentOwner: string;
        fatherId: string;
        motherId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintCertificate"
  ): TypedContractMethod<
    [
      _id: string,
      _variety: string,
      _breeder: string,
      _gender: string,
      _age: string,
      _size: BigNumberish,
      _condition: string,
      _photoUrl: string,
      _certUrl: string,
      _contestUrl: string,
      _fatherId: string,
      _motherId: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<
    [
      _id: string,
      _newOwner: AddressLike,
      _newOwnerName: string,
      _newSize: BigNumberish,
      _newAge: string,
      _newCondition: string,
      _newPhotoUrl: string,
      _note: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateKoiStats"
  ): TypedContractMethod<
    [
      _id: string,
      _newSize: BigNumberish,
      _newAge: string,
      _newCondition: string,
      _newPhotoUrl: string,
      _newContestUrl: string,
      _updateNote: string
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "KoiMinted"
  ): TypedContractEvent<
    KoiMintedEvent.InputTuple,
    KoiMintedEvent.OutputTuple,
    KoiMintedEvent.OutputObject
  >;
  getEvent(
    key: "KoiUpdated"
  ): TypedContractEvent<
    KoiUpdatedEvent.InputTuple,
    KoiUpdatedEvent.OutputTuple,
    KoiUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "KoiMinted(string,address)": TypedContractEvent<
      KoiMintedEvent.InputTuple,
      KoiMintedEvent.OutputTuple,
      KoiMintedEvent.OutputObject
    >;
    KoiMinted: TypedContractEvent<
      KoiMintedEvent.InputTuple,
      KoiMintedEvent.OutputTuple,
      KoiMintedEvent.OutputObject
    >;

    "KoiUpdated(string,uint256,string,address)": TypedContractEvent<
      KoiUpdatedEvent.InputTuple,
      KoiUpdatedEvent.OutputTuple,
      KoiUpdatedEvent.OutputObject
    >;
    KoiUpdated: TypedContractEvent<
      KoiUpdatedEvent.InputTuple,
      KoiUpdatedEvent.OutputTuple,
      KoiUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(string,address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
